{% set name = "jftools" %}
{% set version = "0.4.1" %}
{% set sha256 = "87539e752288fa8d943a6a8476dbb37922aaa240885565880158aa7daf49ba0b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --record record.txt
  noarch: python

requirements:
  build:
    - python >=3.5
  run:
    - python >=3.5
    - numpy >=1.11
    - scipy
    - nbformat
    - ipython
    - numba
    - matplotlib
    - qutip
test:
  imports:
    - jftools

about:
  home: http://github.com/jfeist/jftools
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Collection of small useful helper tools for Python by Johannes Feist'

extra:
  recipe-maintainers:
    - jfeist
