{% set name = "jftools" %}
{% set version = "0.4.2" %}
{% set sha256 = "e9b3f145c2e79a7c12577009d8ce3df8809ecef4dc356730c3e2bf6a991a1bc8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: python setup.py install --record record.txt
  noarch: python

requirements:
  build:
    - python >=3.5
  run:
    - python >=3.5
    - numpy >=1.11
    - scipy
    - nbformat
    - ipython
    - numba
    - matplotlib-base
    - qutip
test:
  imports:
    - jftools

about:
  home: http://github.com/jfeist/jftools
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Collection of small useful helper tools for Python by Johannes Feist'

extra:
  recipe-maintainers:
    - jfeist
