# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "VTTkGsUwRgtxf6pujCh56YHFztf4x4QX4Ujw6OiND58/e5tYn/DIwc3JkfSyGsb9i0MqSD2GHqhGEl1yFXf2m0L+9DBM7Ob1LVTsThK52Y6/DqxSIuQeebRNFW3039Pm9lAS/DrK2f+sSVlN80+tSzUNc3tjhoyc+c46SguY0gv4HnulQvvxp0BJZdCFlE9JVCY0lgorJfJL5085xSMLfbvErH1xBvVMWEg6slklC4Dnb1bQY2/a8jCQK+gJ3N2CSnoQv8nCiYyXHHeadP28zK+COKWO8pBCWZZnIoB9HrscutQVD55ZUKo3uN7us9kRkJoj7HU+fOieSI36qe0IRAJc2iT9lAawGl/PB6XBYL7u9sCd1ZmTyjtgecQpPSlPP4g9E8fHqrxGDBqCVQaK2OodYuoIsaqUrVlQzAhQgKJmCiC5t/jPLssQYBCMUuuaw15ExvDzSqqX3IF8E72wz0V3/y2IS3jmu/TsW+LwnUC0iNmNTXumWVZw9604YQ9B4wMjQSUdMFJtMlcTXCCVtmeKE8OwWvWhYidjm6bsw+M8JkjzM/tEXuB1oPChpIN1ujZUgRu/PthtV4d0XaJNgx/O3O58wxDhhcReEWi2904hWFTWlUJkjDybp5Rr44WTD9HE3A3+moz6vKtdTj3UDvO8Pv8Xg+gRCtlNByCRdcU="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
