travis:
  secure:
    BINSTAR_TOKEN: VTTkGsUwRgtxf6pujCh56YHFztf4x4QX4Ujw6OiND58/e5tYn/DIwc3JkfSyGsb9i0MqSD2GHqhGEl1yFXf2m0L+9DBM7Ob1LVTsThK52Y6/DqxSIuQeebRNFW3039Pm9lAS/DrK2f+sSVlN80+tSzUNc3tjhoyc+c46SguY0gv4HnulQvvxp0BJZdCFlE9JVCY0lgorJfJL5085xSMLfbvErH1xBvVMWEg6slklC4Dnb1bQY2/a8jCQK+gJ3N2CSnoQv8nCiYyXHHeadP28zK+COKWO8pBCWZZnIoB9HrscutQVD55ZUKo3uN7us9kRkJoj7HU+fOieSI36qe0IRAJc2iT9lAawGl/PB6XBYL7u9sCd1ZmTyjtgecQpPSlPP4g9E8fHqrxGDBqCVQaK2OodYuoIsaqUrVlQzAhQgKJmCiC5t/jPLssQYBCMUuuaw15ExvDzSqqX3IF8E72wz0V3/y2IS3jmu/TsW+LwnUC0iNmNTXumWVZw9604YQ9B4wMjQSUdMFJtMlcTXCCVtmeKE8OwWvWhYidjm6bsw+M8JkjzM/tEXuB1oPChpIN1ujZUgRu/PthtV4d0XaJNgx/O3O58wxDhhcReEWi2904hWFTWlUJkjDybp5Rr44WTD9HE3A3+moz6vKtdTj3UDvO8Pv8Xg+gRCtlNByCRdcU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
