travis:
  secure:
    BINSTAR_TOKEN: F+Ol2RYgKV+wb3qIu+PCWvxmfKY9MBNbj/xqYCr1UfCBzd5j+vqvum6ugg37Y4g6o6zhOtGv64fUERk30M+1iQqh3b3Mz+3yC+YOA05Su8xWttkyFasJeYez8JzkO4oUVPIhtzKixxOLIeX7ye3Y4rPDhnIhp5SZyPF5fPnYHwPMTSFq1aTn6f3EASV9fCdtPhXK1rc96ovzN2YJ4T6WIBqYko5g6ihIqZ+/5jfIstNY8HySjDtIOoFvdv4wkl5D2N7YLATEhdNyfuTdWo4mpTeeSf2mrgT+1neQZqviO/HHUw+0HeF7Eksg2FlGR24X+yePx9+0IVnfQRMl4TFw1hxZofMGgEkuMaYr5Mb/7VFL2YOcvjtQFii9LkEYgHOP6Ez9oUtd5IjcjIVZBQvudBknyQQ6rYqQpIaXN0E8+cNhL2k8cH7Cybha8icoztbRcQvYYAskQCuF98XqrrhQugMTl3uiRSG5MsAd0DGOOx8Oyz9Ig48P/ayhYj7OhR8ARLsuzm6GwcFF8wpdJB83zDgewZkDcryIH5a5iPCM6xcDVlVOuw+jkgKK9+6peJEI1Gj/6S4a1Z2uY9QYCmkuOyNHQ4UKoOSgPAj63d/HjKvj/WMvAG/eoyoJKDLub/Hnt1gcXMWVwBM137HcVQp5HGGKNswSf0GBOo2Cq/S8iGs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
